DROP TABLE IF EXISTS USER;

CREATE TABLE USER (
  ID int(11) NOT NULL AUTO_INCREMENT,
  LOGIN_ID varchar(200) NOT NULL,
  PASSWORD VARCHAR (1000) NOT NULL,
  AGENCY_NAME varchar(200) DEFAULT NULL,
  PRESIDENT_NAME varchar(200) DEFAULT NULL,
  AGENCY_ADDRESS varchar(200) DEFAULT NULL,
  BUSINESS_NUMBER varchar(200) DEFAULT NULL,
  PHONE_NUMBER varchar(200) DEFAULT NULL,
  MOBILE_PHONE_NUMBER varchar(200) DEFAULT NULL,
  CREATED_ON datetime default NULL,
  LAST_MODIFIED_ON datetime default NULL,
  ACTIVATION char(1) DEFAULT '1',
  PRIMARY KEY (ID)
);

DROP TABLE IF EXISTS ROLE;

CREATE TABLE ROLE (
  ID int(11) NOT NULL AUTO_INCREMENT,
  LOGIN_ID varchar(200) NOT NULL,
  ROLE varchar(200) NOT NULL,
  CREATED_BY varchar(200) NOT NULL,
  LAST_MODIFIED_BY varchar(200) NOT NULL,
  CREATED_ON datetime default NULL,
  LAST_MODIFIED_ON datetime default NULL,
);

DROP TABLE IF EXISTS PRODUCT;

CREATE TABLE PRODUCT (
  ID int(11) NOT NULL AUTO_INCREMENT,
  PRODUCT_CODE varchar(50) NOT NULL,
  PRODUCT_NAME varchar(200) NOT NULL,
  CREATED_BY varchar(200) NOT NULL,
  LAST_MODIFIED_BY varchar(200) NOT NULL,
  CREATED_ON datetime default NULL,
  LAST_MODIFIED_ON datetime default NULL,
  PRIMARY KEY (ID)
);

DROP TABLE IF EXISTS SALE;

CREATE TABLE SALE (
  ID int(11) NOT NULL AUTO_INCREMENT,
  SERIAL_NUMBER varchar(200) NOT NULL,
  SALES_ON datetime default NULL,
  CREATED_BY varchar(200) NOT NULL,
  LAST_MODIFIED_BY varchar(200) NOT NULL,
  CREATED_ON datetime default NULL,
  LAST_MODIFIED_ON datetime default NULL,
  PRIMARY KEY (ID)
);